.PHONY: build-server build-client

default: build-server build-client

build-server:
	go build -o ./bin/lynxmcpserver ./server/lynxmcpserver.go

build-client:
	go build -o ./bin/lynxmcpclient ./client/lynxmcpclient.go
