drop table if exists emails;

create table emails (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  content text null,
  fts tsvector,
  embedding vector(1536) not null,
  metadata jsonb null,
  constraint emails_pkey primary key (id)
) TABLESPACE pg_default;

comment on table emails IS 'Pan PAC emails knowledge (hybrid search)';

create or replace function emails_fts_trigger() returns trigger as $$
begin
  new.fts := to_tsvector(
    COALESCE(new.metadata->>'inferredLanguage', 'english')::regconfig,
    new.content
  );
  return new;
end
$$ language plpgsql;

create or replace trigger tsvectorupdate before insert or update
on emails for each row execute function emails_fts_trigger();

create index emails_fts_idx on emails using gin (fts);

create index emails_embedding_idx on emails using hnsw (embedding vector_cosine_ops);
