drop table if exists panpac.emails_dev;

create table panpac.emails_dev (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  content text null,
  embedding vector(1536) not null,
  metadata jsonb null,
  constraint emails_dev_pkey primary key (id)
) TABLESPACE pg_default;

comment on table panpac.emails_dev IS 'Pan PAC emails knowledge DEV (semantic search)';

create index emails_dev_embedding_idx on panpac.emails_dev using hnsw (embedding vector_cosine_ops);

drop table if exists panpac.emails_prod;

create table panpac.emails_prod (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  content text null,
  embedding vector(1536) not null,
  metadata jsonb null,
  constraint emails_prod_pkey primary key (id)
) TABLESPACE pg_default;

comment on table panpac.emails_prod IS 'Pan PAC emails knowledge PROD (semantic search)';

create index emails_prod_embedding_idx on panpac.emails_prod using hnsw (embedding vector_cosine_ops);
