drop table if exists emails;

create table emails (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  content text null,
  embedding vector(1536) not null,
  metadata jsonb null,
  constraint emails_pkey primary key (id)
) TABLESPACE pg_default;

comment on table emails IS 'Pan PAC emails knowledge (semantic search)';

create index emails_embedding_idx on emails using hnsw (embedding vector_cosine_ops);
