drop table if exists public.emails;

create table public.emails (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  inferred_language varchar(255) not null check (inferred_language in ('english', 'french')),
  content text null,
  fts tsvector,
  embedding public.vector(512) not null,
  metadata jsonb null,
  constraint emails_pkey primary key (id)
) TABLESPACE pg_default;

create or replace function emails_fts_trigger() returns trigger as $$
begin
  new.fts := to_tsvector(new.inferred_language::regconfig, new.content);
  return new;
end
$$ language plpgsql;

create trigger tsvectorupdate before insert or update
on public.emails for each row execute function emails_fts_trigger();
