name: Publish Docker image

on:
  push:
    branches: [ master ]

jobs:
  build-and-push-lynx-mcp-server-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build lynx-mcp-server -t ghcr.io/fredguile/lynx-mcp-server:latest
          docker push ghcr.io/fredguile/lynx-mcp-server:latest